version: '3.8'

services:
  nseindia:
    image: imcodeman/nseindia
    ports:
      - "3001:3001"

  mcp:
    build: .
    ports:
      - "8000:8000"
      - "8080:8080"
    depends_on:
      - nseindia
